### PR TITLE
Bring docker dev branch upto date

### PR DESCRIPTION
**Pull request by samjijina**
this PR is to bring docker dev branch up to date with the latest changes to PIN enumerators

### CODE REVIEW

**Comment by hyojongk** [comment]
I don't understand why this branch has to be up-to-date with pin branch? I might be wrong but isn't this branch for making a docker image for sst-macsim?

**Comment by samjijina** [comment]
> I don't understand why this branch has to be up-to-date with pin branch? I might be wrong but isn't this branch for making a docker image for sst-macsim?

Because when we build docker image, we need to run all commands and ensure they work so need an up-to-date copy of pin

**Comment by hyojongk** [comment]
I disagree with that. Keep this independent of Pin update. Otherwise it's going to be very hard to rebase and merge this and the new pin branch onto the master branch.

**Comment by samjijina** [comment]
> I disagree with that. Keep this independent of Pin update. Otherwise it's going to be very hard to rebase and merge this and the new pin branch onto the master branch.

I see, you're right

**Pull request closed without merging**
